onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /lab7_check_tb/DUT/CPU/clk
add wave -noupdate /lab7_check_tb/DUT/CPU/reset
add wave -noupdate /lab7_check_tb/DUT/CPU/s
add wave -noupdate /lab7_check_tb/DUT/CPU/load
add wave -noupdate /lab7_check_tb/DUT/CPU/in
add wave -noupdate /lab7_check_tb/DUT/CPU/mdata
add wave -noupdate /lab7_check_tb/DUT/CPU/out
add wave -noupdate /lab7_check_tb/DUT/CPU/N
add wave -noupdate /lab7_check_tb/DUT/CPU/V
add wave -noupdate /lab7_check_tb/DUT/CPU/Z
add wave -noupdate /lab7_check_tb/DUT/CPU/w
add wave -noupdate /lab7_check_tb/DUT/CPU/mem_addr
add wave -noupdate /lab7_check_tb/DUT/CPU/mem_cmd
add wave -noupdate /lab7_check_tb/DUT/CPU/present_state_out
add wave -noupdate /lab7_check_tb/DUT/CPU/decoder_in
add wave -noupdate /lab7_check_tb/DUT/CPU/nsel
add wave -noupdate /lab7_check_tb/DUT/CPU/opcode
add wave -noupdate /lab7_check_tb/DUT/CPU/readnum
add wave -noupdate /lab7_check_tb/DUT/CPU/writenum
add wave -noupdate /lab7_check_tb/DUT/CPU/ALUop
add wave -noupdate /lab7_check_tb/DUT/CPU/op
add wave -noupdate /lab7_check_tb/DUT/CPU/shift
add wave -noupdate /lab7_check_tb/DUT/CPU/vsel
add wave -noupdate /lab7_check_tb/DUT/CPU/sximm5
add wave -noupdate /lab7_check_tb/DUT/CPU/sximm8
add wave -noupdate /lab7_check_tb/DUT/CPU/loada
add wave -noupdate /lab7_check_tb/DUT/CPU/loadb
add wave -noupdate /lab7_check_tb/DUT/CPU/loadc
add wave -noupdate /lab7_check_tb/DUT/CPU/asel
add wave -noupdate /lab7_check_tb/DUT/CPU/bsel
add wave -noupdate /lab7_check_tb/DUT/CPU/write
add wave -noupdate /lab7_check_tb/DUT/CPU/loads
add wave -noupdate /lab7_check_tb/DUT/CPU/load_pc
add wave -noupdate /lab7_check_tb/DUT/CPU/reset_pc
add wave -noupdate /lab7_check_tb/DUT/CPU/addr_sel
add wave -noupdate /lab7_check_tb/DUT/CPU/load_ir
add wave -noupdate /lab7_check_tb/DUT/CPU/load_addr
add wave -noupdate /lab7_check_tb/DUT/CPU/shiftsel
add wave -noupdate /lab7_check_tb/DUT/CPU/PC_sus
add wave -noupdate /lab7_check_tb/DUT/CPU/PC
add wave -noupdate /lab7_check_tb/DUT/CPU/adder_out
add wave -noupdate /lab7_check_tb/DUT/CPU/next_pc
add wave -noupdate /lab7_check_tb/DUT/CPU/LDR_out
add wave -noupdate /lab7_check_tb/DUT/CPU/fsm_controller/s
add wave -noupdate /lab7_check_tb/DUT/CPU/fsm_controller/reset
add wave -noupdate /lab7_check_tb/DUT/CPU/fsm_controller/clk
add wave -noupdate /lab7_check_tb/DUT/CPU/fsm_controller/opcode
add wave -noupdate /lab7_check_tb/DUT/CPU/fsm_controller/op
add wave -noupdate /lab7_check_tb/DUT/CPU/fsm_controller/nsel
add wave -noupdate /lab7_check_tb/DUT/CPU/fsm_controller/mem_cmd
add wave -noupdate /lab7_check_tb/DUT/CPU/fsm_controller/vsel
add wave -noupdate /lab7_check_tb/DUT/CPU/fsm_controller/shiftsel
add wave -noupdate /lab7_check_tb/DUT/CPU/fsm_controller/loada
add wave -noupdate /lab7_check_tb/DUT/CPU/fsm_controller/loadb
add wave -noupdate /lab7_check_tb/DUT/CPU/fsm_controller/loadc
add wave -noupdate /lab7_check_tb/DUT/CPU/fsm_controller/asel
add wave -noupdate /lab7_check_tb/DUT/CPU/fsm_controller/bsel
add wave -noupdate /lab7_check_tb/DUT/CPU/fsm_controller/write
add wave -noupdate /lab7_check_tb/DUT/CPU/fsm_controller/loads
add wave -noupdate /lab7_check_tb/DUT/CPU/fsm_controller/load_pc
add wave -noupdate /lab7_check_tb/DUT/CPU/fsm_controller/reset_pc
add wave -noupdate /lab7_check_tb/DUT/CPU/fsm_controller/addr_sel
add wave -noupdate /lab7_check_tb/DUT/CPU/fsm_controller/load_ir
add wave -noupdate /lab7_check_tb/DUT/CPU/fsm_controller/load_addr
add wave -noupdate /lab7_check_tb/DUT/CPU/fsm_controller/w
add wave -noupdate /lab7_check_tb/DUT/CPU/fsm_controller/present_state_out
add wave -noupdate /lab7_check_tb/DUT/CPU/DP/REGFILE/R0
add wave -noupdate /lab7_check_tb/DUT/CPU/DP/REGFILE/R1
add wave -noupdate /lab7_check_tb/DUT/CPU/DP/REGFILE/R2
add wave -noupdate /lab7_check_tb/DUT/CPU/DP/REGFILE/R3
add wave -noupdate /lab7_check_tb/DUT/CPU/DP/REGFILE/R4
add wave -noupdate /lab7_check_tb/DUT/CPU/DP/REGFILE/R5
add wave -noupdate /lab7_check_tb/DUT/CPU/DP/REGFILE/R6
add wave -noupdate /lab7_check_tb/DUT/CPU/DP/REGFILE/R7
add wave -noupdate /lab7_check_tb/DUT/MEM/mem
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {270 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {9 ps} {281 ps}
